apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
  namespace: kapp
spec:
  type: {{ .Values.backendservice.type }}
  ports:
    - port: {{ .Values.backendservice.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    name: backend