apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  type: {{ .Values.backend-service.type }}
  ports:
    - port: {{ .Values.backend-service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    name: backend