apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: db
  namespace: kapp
spec:
  type: {{ .Values.dbservice.type }}
  ports:
    - port: {{ .Values.dbservice.port }}
      targetPort: 5432
      protocol: TCP
      name: http
  selector:
    name: db
