apiVersion: v1
kind: Service
metadata:
    name: frontend
    labels:
      app: frontend
    namespace: kapp
spec:
  type: {{ .Values.frontendservice.type }}
  ports:
    - port: {{ .Values.frontendservice.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    name: frontend